#!/usr/bin/env python3
"""Assemble production/ — every artefact meant to run in a real deployment.

    python3 tools/build_production.py

One folder holding what a deployment needs, so the PoC scaffolding cannot be shipped by
accident. Nothing here is substituted: the production catalog, service principals and
groups are not this repo's to guess.

WHAT IS DELIBERATELY EXCLUDED, and it is most of the repo: `fixtures/` (a laptop
dataset), `sql/out/` (rendered for one sandpit, plus mock source tables, a fixture seed,
39 fabricated runs, a check-runner stand-in and a comparison harness), and
`sql/out/migrate_fn_adoption.sql` (a one-time repair for a catalog seeded before the
shared helpers existed -- a deployment authored against them never needs it).

THE APP IS NOT COPIED HERE, on purpose. `dq-app/` deploys with `databricks sync` and is
the only directory that ships; duplicating ~20 modules that 129 tests are pinned to
would create a second copy that drifts silently. The README points at it instead.
"""

from __future__ import annotations

import pathlib
import shutil

ROOT = pathlib.Path(__file__).parent.parent
OUT = ROOT / "production"

# (source, destination, why it is here). SQL order is load-bearing.
SQL = [
    ("sql/ddl/00_schemas.sql",               "catalog and the two schemas"),
    ("sql/ddl/01_config_rule_registry.sql",  "what we check — append-only"),
    ("sql/ddl/02_config_playbook.sql",       "remediation approaches, non-executable by design"),
    ("sql/ddl/03_results_check_run.sql",     "one verdict per rule per run"),
    ("sql/ddl/04_results_violation_sample.sql", "<=100 example bad rows per breach"),
    ("sql/ddl/05_results_cohort.sql",        "grouped breaches + the model's verdict"),
    ("sql/ddl/06_results_disposition.sql",   "THE AUDIT REGISTER — append-only"),
    ("sql/ddl/09_config_cde_registry.sql",   "what matters — registered before anything profiles it"),
    ("sql/ddl/10_results_cde_profile.sql",   "what each registered element contains"),
    ("sql/ddl/12_functions.sql",             "shared predicate helpers — 13 rules CALL these, "
                                             "so this must precede any registry seed"),
    ("sql/ddl/13_results_threshold.sql",     "the threshold job's advice, and the reviewer's "
                                             "decision on it — the app's third write"),
    ("sql/ddl/08_views.sql",                 "current state, derived — reads 01 and 06"),
    ("sql/ddl/11_views_cde.sql",             "coverage — reads 09, 10, 03 and 08's view"),
    ("sql/ddl/14_views_threshold.sql",       "where each rule's latest proposal has got to — "
                                             "reads 13 and 08's view"),
    ("sql/ddl/15_config_onboarding.sql",     "which tables are checked, check templates, and "
                                             "binding proposals and decisions — append-only"),
    ("sql/ddl/16_views_onboarding.sql",      "how far each selected table has got — reads 15, "
                                             "08's view and 11's"),
    ("sql/ddl/07_grants.sql",                "the control claim. Last, because it grants on "
                                             "objects that must already exist"),
]

OTHER = [
    ("jobs/run_checks.py", "jobs/run_checks.py",
     "**Scheduled in `workspace.dq_onboard` only** (the `dq-checks` job, daily). The check "
     "runner. One aggregate per table rather than one query per rule; checks the tables "
     "`config.monitored_table` selects. Verdict logic validated against a real catalog by "
     "`jobs/validate_run_checks.py`."),
    ("notebooks/03_group_and_advise.ipynb", "notebooks/03_group_and_advise.ipynb",
     "**Executed.** The triage job: groups breaches mechanically, reads the register, "
     "calls a model once per group, writes `results.cohort`."),
    ("notebooks/04_send_notification.ipynb", "notebooks/04_send_notification.ipynb",
     "**Never executed.** The mail sender behind `DQ_NOTIFY=job`. Needs a job, a secret "
     "scope and an SMTP host that do not exist. Writes no table."),
    ("notebooks/06_suggest_thresholds.ipynb", "notebooks/06_suggest_thresholds.ipynb",
     "**Never executed.** The threshold job: one model call per registered element, "
     "advising on each rule's fail_threshold_pct against the element's declared tolerance "
     "and the run history. Writes `results.threshold_proposal` and nothing else."),
]

README = """# production/ — GENERATED by tools/build_production.py. Do not edit; regenerate.

Every artefact meant to run in a real deployment, and nothing else. Excluded on purpose:
`fixtures/` (a laptop dataset) and all of `sql/out/` (rendered for one sandpit, plus mock
source tables, a fixture seed, 39 fabricated check runs, a check-runner stand-in and a
comparison harness).

## Status, honestly

| Artefact | Has it run? |
|---|---|
| `sql/` — 17 DDL files | **Yes**, as the rendered single-schema variant: 01–14 against `workspace.dq_triage`, the onboarding pair (15, 16) against `workspace.dq_onboard` only |
| `notebooks/03_group_and_advise.ipynb` | **Yes**, as a serverless job against `system.ai.gpt-oss-120b` |
| `jobs/run_checks.py` | **Yes, scheduled — in `workspace.dq_onboard` only** (the `dq-checks` job, daily). Nothing runs it against `dq_triage` |
| `notebooks/04_send_notification.ipynb` | **No.** Needs a job, a secret scope and an SMTP host |
| The Streamlit app | **Yes**, deployed — but from `dq-app/`, not from here. See below |

## The app is not in this folder

`dq-app/` deploys on its own and is the only directory that ships:

```bash
databricks sync . /Workspace/Users/<you>/dq-app-src
databricks apps deploy dq-triage --source-code-path /Workspace/Users/<you>/dq-app-src
```

It is not duplicated here because ~20 modules that 129 tests are pinned to would become a
second copy that drifts. Two things to know for a real deployment: `app.yaml` must point
at the production catalog, and `dq_app/fixture_data/` is the **local demo bundle** — it
exists only so the self-contained demo can run inside a container and must not be what a
production app reads.

### TODO before deploying to a company workspace (noted 2026-10-01, not started)

Checked against the code on 2026-10-01: at run time the app talks only to its own
workspace (the SQL warehouse through `databricks-sql-connector`, the Jobs API through
`databricks-sdk` when notifications are on). There are no external APIs, fonts or CDNs, and
Streamlit telemetry is off. Restricted serverless egress should not break it. What will
break it is the list below.

* [ ] **Ask the workspace admin about PyPI.** The deploy runs `pip install` on
  `dq-app/requirements.txt` (five packages). If serverless egress is in restricted mode
  and `pypi.org` is not allowed, the build fails. Find out whether there is an internal
  mirror (Artifactory, Nexus), and point the deploy at it: the workspace's default package
  repository, or `--index-url` at the top of `requirements.txt`.
* [ ] **Rewrite `dq-app/app.yaml` for the company workspace.** Every value in it
  currently points at the personal workspace:
  * `DQ_CATALOG` / `DQ_SCHEMA` / `DQ_PREFIX`: set these to where the DDL was run, or drop
    `DQ_SCHEMA` to use the two-schema layout.
  * `DQ_NOTIFY`: set to `off` or `log` for the first deploy. `job` with a job id that
    does not exist fails silently, because the transport logs and swallows errors.
  * `DQ_NOTIFY_JOB_ID`, `DQ_NOTIFY_TO` (currently a personal address) and `DQ_APP_URL`:
    replace all three, or remove them.
* [ ] **Prerequisites in the target workspace:** the DDL run in the target catalog, a SQL
  warehouse attached to the App under the resource key `sql-warehouse`, and the App's
  service principal holding the grants in `sql/16_grants.sql`.
* [ ] **After the first deploy**, check `system.access.outbound_network` for rows with
  `network_source_type = 'Apps'`. Any rows there are connections the App attempted and
  the egress policy denied. Denials to `login.microsoftonline.com` with source `unknown`
  were seen in the personal workspace and are not this app.

## Substitute before running any SQL

| Placeholder | What it is |
|---|---|
| `{catalog}` | the catalog holding `config` and `results` (103 occurrences) |
| `{app_sp}` | the app's service principal. Gets `MODIFY` on exactly six tables — three of them onboarding's, which is a decision; comment those out to deploy without it |
| `{check_runner_sp}` | the check runner's principal. Gets `EXECUTE` on `{catalog}.fn` and nothing else |
| `{steward_group}` | who may author rules and record a review |
| `{approver_group}` | who may approve. **Unresolved in the spec — see below** |

`{table}` in `sql/09_functions.sql` is NOT one of these. It appears inside a comment
describing a variance `rule_expr`, and the check runner substitutes it at run time.

## Order is load-bearing

Run `sql/` top to bottom. Two dependencies are easy to get wrong:

* **`09_functions.sql` must precede any seeding of `config.rule_registry`.** Thirteen
  rules call `{catalog}.fn.is_blank_v1`, `is_valid_email_v1`, `is_au_mobile_v1` or
  `is_sentinel_v1`. A registry seeded into a catalog without them holds rules the check
  runner cannot execute, and nothing in the schema will tell you.
* **Views last.** `11_views_cde.sql` reads the CDE tables, `check_run`, and the view
  `10_views.sql` creates. It fails if any is missing.

`ALTER TABLE … ADD CONSTRAINT` is **not idempotent**. Run each file once.

Then: seed `config.rule_registry` and `config.cde_registry`, schedule
`jobs/run_checks.py`, schedule `notebooks/03_group_and_advise.ipynb` after it, deploy the
app.

## Still missing, and none of it is a schema change

* **The profile job.** Nothing writes `results.cde_profile`. No profiler has ever run in
  a warehouse — the PoC's 12 rows are a laptop's pandas output, loaded verbatim.
* **`join_sql` on `config.rule_registry`.** Three cross-table rules carry a join the
  registry has no column to hold, so `jobs/run_checks.py` keeps them in a hardcoded dict
  and writes `status = 'error'` for any it cannot resolve. Fix this first.
* **`MODIFY` on `results.cohort` for the triage principal.** Not in `sql/16_grants.sql`.
  Without it notebook 03 cannot open the chain it creates, and every cohort it writes is
  reported by `v_disposition_integrity` as `missing_recommended_event`.
* **`function_version` on `results.check_run`.** Rules now depend on functions, and a
  verdict cannot say which version produced it. `CREATE OR REPLACE` on a referenced
  helper silently rewrites the meaning of every past verdict. Keep `{catalog}.fn` owned
  by the platform team with `EXECUTE` only — that ownership is the whole enforcement.
* **`XREF_NAME_AGREEMENT` under-reports.** Its `<>` is not null-safe, so it returns 0
  where the reference implementation returns 2. `XREF_OPEN_TS_AGREEMENT` has the same
  pattern latently. Do not schedule a runner on top of a rule you know is wrong.

## Two questions the grants file cannot answer

* **Who may approve.** `{approver_group}` must resolve to a governed group or the
  two-distinct-approver control is decorative: the app can count two identities, but
  nobody has said which identities are eligible.
* **Detective or preventive.** This register records that named people approved and that
  someone reported executing. It cannot prevent execution without approval. If it covers
  regulated data, prevention belongs in change management and production grants, not
  here. Do not present these files as providing it.

## Contents

"""


def main() -> int:
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "sql").mkdir(parents=True)
    rows = ["| # | File | Why here |", "|---|---|---|"]
    for i, (src, why) in enumerate(SQL):
        name = pathlib.Path(src).name
        dst = OUT / "sql" / f"{i:02d}_{name[3:]}"
        dst.write_text(
            f"-- DEPLOY STEP {i:02d} of {len(SQL) - 1} — copied from {src}\n"
            f"-- by tools/build_production.py. Placeholders are NOT substituted.\n--\n"
            + (ROOT / src).read_text())
        rows.append(f"| {i:02d} | `sql/{dst.name}` | {why} |")
        print(f"  sql/{dst.name:34} <- {src}")
    rows.append("")
    rows += ["| Artefact | What it is |", "|---|---|"]
    for src, rel, why in OTHER:
        dst = OUT / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(ROOT / src, dst)
        rows.append(f"| `{rel}` | {why} |")
        print(f"  {rel:38} <- {src}")
    (OUT / "README.md").write_text(README + "\n".join(rows) + "\n")
    print(f"\nwrote {len(SQL)} SQL + {len(OTHER)} other + README.md to production/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
