#!/usr/bin/env python3
r"""Generate the migration that points 13 rules at the shared UC predicate helpers.

    python3 sql/migrate_fn.py --catalog workspace --schema dq_triage --prefix dq_

Writes sql/out/migrate_fn_adoption.sql. Generated and gitignored-adjacent like every
other file in sql/out/: the fixture is the source of the new expressions, and hand-
writing 13 INSERTs over 21 columns is exactly what seed.py exists to avoid.

WHY A MIGRATION AND NOT A RE-SEED

config.rule_registry is `delta.appendOnly = true`. DELETE is blocked, so seed.sql
cannot be re-run against a loaded registry -- it would either fail or duplicate v1.
Adopting a function is therefore a NEW rule_version, which is the discipline the
registry already has and the reason it has it.

The version is computed per rule from what is actually in the table, not assumed to
be 2: SUBS_MSISDN_FMT already carries v1 and v2 (its scope_filter fix), so it goes to
v3 while the other twelve go to v2.

The fixture now models the same bump -- longhand at v1, the helper at v2 (v3 for
MSISDN) -- so the version carried by the fixture IS the target this writes, and the
`rule_version + 1` below must land on it. Step 2a checks that, rather than trusting
the two to have stayed in step.

WHAT EACH INSERT CARRIES FORWARD, AND WHAT IT CHANGES

An INSERT ... SELECT off the current version, so nothing drifts. Changed:

  rule_version      +1
  rule_expr         the function call
  effective_from    now
  created_by/at     current_user(), now -- "authoring identity ... when this version
                    was authored" per the DDL, and this version is authored now
  note              why, and that equivalence was proven

Carried forward verbatim -- including the two that matter:

  status            shadow STAYS shadow. SUBS_BNFT_TXT_NOT_NULL is one of the two
                    shadow rules the fixture needs; promoting it here would change
                    the rule set under cover of a refactor.
  promoted_by/at    NULL on a shadow rule, and left alone on an active one. A new
                    version of an already-active rule is not a shadow->active
                    promotion, and WHO may sign one off is an open question in the
                    spec that this file must not answer by implication.

  scope_filter      untouched. SUBS_IMEI_NOT_NULL and SUBS_PRIM_ACCT_NOT_ZERO stay
                    deliberately unscoped -- see CLAUDE.md. This migration changes
                    how a predicate is written and nothing about what it measures.

THERE IS NO ROLLBACK, BY CONSTRUCTION. appendOnly means reverting is another INSERT
carrying the longhand back, at version+1. Budget a forward fix, not an undo.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import pandas as pd

ROOT = pathlib.Path(__file__).parent.parent
FIX = ROOT / "fixtures" / "out"
OUT = pathlib.Path(__file__).parent / "out"
sys.path.insert(0, str(ROOT / "fixtures"))

FN_NAMES = ("is_blank_v1", "is_valid_email_v1", "is_au_mobile_v1", "is_sentinel_v1")


def sql_str(v: str) -> str:
    """A Spark SQL string literal. Backslashes must survive -- see seed.py's header;
    none of the 13 new expressions contains one, and this keeps it that way if one
    ever does."""
    return "'" + str(v).replace("\\", "\\\\").replace("'", "\\'") + "'"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", default="workspace")
    ap.add_argument("--schema", default="dq_triage")
    ap.add_argument("--prefix", default="dq_")
    ap.add_argument("--src-prefix", default="dq_mock_")
    ap.add_argument("--fn-prefix", default=None,
                    help="Replaces `dq.fn.` in rule_expr. Must be the SAME value "
                         "seed.py and checkrun.py were run with.")
    a = ap.parse_args()

    q = f"{a.catalog}.{a.schema}."
    reg = f"{q}{a.prefix}config_rule_registry"
    vcur = f"{q}{a.prefix}config_v_rule_registry_current"
    fn = a.fn_prefix or f"{q}{a.prefix}fn_"
    tbl = {
        "prod.customer.ctct_c": f"{q}{a.src_prefix}ctct_c",
        "prod.customer.subs_c": f"{q}{a.src_prefix}subs_c",
    }

    rules = pd.read_parquet(FIX / "config.rule_registry.parquet")
    cur = rules.sort_values("rule_version").groupby("rule_id", as_index=False).tail(1)
    targets = cur[cur["rule_expr"].str.contains("dq.fn.", regex=False)].copy()
    targets["rule_expr"] = targets["rule_expr"].str.replace("dq.fn.", fn, regex=False)
    targets = targets.sort_values("rule_id")

    runs = pd.read_parquet(FIX / "results.check_run.parquet")
    last = runs[runs.run_ts == runs.run_ts.max()].set_index("rule_id")

    p: list[str] = [
        "-- =====================================================================",
        "-- migrate_fn_adoption.sql — GENERATED by sql/migrate_fn.py. Do not edit.",
        f"-- target: {a.catalog}.{a.schema}, prefix {a.prefix}",
        f"-- helpers: {fn}*",
        "--",
        f"-- Points {len(targets)} rules at the shared predicate helpers declared in",
        "-- sql/ddl/12_functions.sql. One INSERT per rule. The registry is appendOnly,",
        "-- so this is a new rule_version and NOT a re-seed. See sql/migrate_fn.py for",
        "-- what each INSERT carries forward and why.",
        "--",
        "-- RUN THE THREE STEP-0 QUERIES FIRST AND READ THEM. Step 0c is the guard",
        "-- against running this twice. There is no rollback.",
        "--",
        "-- The new expressions come from the FIXTURE, so this file states what it",
        "-- will write and never what the catalog currently holds. Step 2a is the",
        "-- query that shows you the live value next to the intended one.",
        "-- =====================================================================",
        "",
        "-- ---------------------------------------------------------------------",
        "-- Step 0a — the helpers exist and this principal may execute them",
        "-- EXPECTED: 4 rows. A missing function means the INSERTs below would",
        "-- write rules the check runner cannot run.",
        "-- ---------------------------------------------------------------------",
        "SELECT routine_name, data_type",
        f"FROM   {a.catalog}.information_schema.routines",
        f"WHERE  routine_catalog = '{a.catalog}' AND routine_schema = '{a.schema}'",
        "  AND  routine_name IN (" + ", ".join(
            sql_str(f"{a.prefix}fn_{n}") for n in FN_NAMES) + ")",
        "ORDER  BY routine_name;",
        "",
        "-- ---------------------------------------------------------------------",
        "-- Step 0b — the helpers behave as 12_functions.sql documents",
        "-- EXPECTED: true, true, NULL, true, false, true, NULL, true",
        "-- The NULLs are load-bearing: is_blank_v1 absorbs NULL, the other three",
        "-- propagate it, and count_if does not count a NULL predicate. If these",
        "-- come back differently, STOP — violation counts will move.",
        "-- ---------------------------------------------------------------------",
        "SELECT",
        f"  {fn}is_blank_v1(NULL)              AS blank_null_true,",
        f"  {fn}is_blank_v1('  ')              AS blank_ws_true,",
        f"  {fn}is_valid_email_v1(NULL)        AS email_null_NULL,",
        f"  {fn}is_valid_email_v1('a.b@c.com') AS email_ok_true,",
        f"  {fn}is_valid_email_v1('a b@c.com') AS email_bad_false,",
        f"  {fn}is_au_mobile_v1('0412345678')  AS mobile_ok_true,",
        f"  {fn}is_sentinel_v1(NULL)           AS sentinel_null_NULL,",
        f"  {fn}is_sentinel_v1('n/a')          AS sentinel_na_true;",
        "",
        "-- ---------------------------------------------------------------------",
        "-- Step 0c — THE GUARD. Has this migration already run?",
        "-- EXPECTED: already_adopted = 0. Any other number means some or all of",
        "-- the INSERTs below have been applied. Re-running would stack another",
        "-- version on top rather than failing. Read before you proceed.",
        "-- ---------------------------------------------------------------------",
        # contains(), not LIKE: the helper prefix holds an underscore, which LIKE
        # treats as a wildcard, and the ESCAPE clause needed to say otherwise puts a
        # backslash in a Spark string literal where it is an escape character.
        # `ESCAPE '\'` does not parse at all. A plain substring test has none of that.
        "SELECT count(*) AS already_adopted",
        f"FROM   {vcur}",
        f"WHERE  contains(rule_expr, {sql_str(fn)});",
        "",
        "-- =====================================================================",
        f"-- Step 1 — the {len(targets)} INSERTs",
        "--",
        "-- Each selects off its own current version, so every column not named",
        "-- here is carried forward unchanged: status (shadow stays shadow),",
        "-- promoted_by/at (NULL on a shadow rule), scope_filter, severity,",
        "-- cde_id, thresholds. rule_version is computed, never assumed.",
        "-- =====================================================================",
    ]

    for _, r in targets.iterrows():
        note = (f"v{int(r.rule_version)}: predicate replaced by the shared helper "
                f"{fn}{[n for n in FN_NAMES if n in r.rule_expr][0]}. Behaviour "
                f"unchanged — sql/out/checkrun.sql was re-run against this catalog "
                f"before and after and returned the identical count for this rule. "
                f"The helper is immutable once referenced: a change is a _v2 function "
                f"plus another rule_version, never an ALTER.")
        p += [
            "",
            f"-- {r.rule_id}  -> v{int(r.rule_version)}   [{r.status}]",
            f"--   sets rule_expr to: {r.rule_expr}",
            "--   (this file does not assert what the catalog holds now — it is",
            "--    generated from the fixture. Step 2a prints the live value.)",
            f"INSERT INTO {reg} SELECT",
            "  rule_id,",
            "  rule_version + 1                    AS rule_version,",
            "  rule_name, target_table, target_column, cde_id, rule_type,",
            f"  {sql_str(r.rule_expr)} AS rule_expr,",
            "  scope_filter, fail_threshold_pct, severity, business_domain,",
            "  owner_group, source_layer,",
            "  status,",
            "  current_timestamp()                 AS effective_from,",
            "  current_user()                      AS created_by,",
            "  current_timestamp()                 AS created_at,",
            "  promoted_by, promoted_at,",
            f"  {sql_str(note)} AS note",
            f"FROM   {reg}",
            f"WHERE  rule_id = {sql_str(r.rule_id)}",
            f"  AND  rule_version = (SELECT max(rule_version) FROM {reg}",
            f"                       WHERE rule_id = {sql_str(r.rule_id)});",
        ]

    # ---- Step 2: prove it -------------------------------------------------
    p += [
        "",
        "-- =====================================================================",
        "-- Step 2 — verification. All three are read-only.",
        "-- =====================================================================",
        "",
        "-- 2a — the current version of each rule now calls a helper.",
        f"-- EXPECTED: {len(targets)} rows, every verdict OK.",
        "SELECT rule_id, rule_version, exp_version, status, rule_expr,",
        "       CASE WHEN rule_expr = expected AND rule_version = exp_version",
        "            THEN 'OK' ELSE 'MISMATCH' END AS verdict",
        "FROM   (SELECT * FROM " + vcur + ") c",
        "JOIN   (VALUES",
    ]
    vals = [f"         ({sql_str(r.rule_id)}, {int(r.rule_version)}, "
            f"{sql_str(r.rule_expr)})" for _, r in targets.iterrows()]
    p += [",\n".join(vals),
          "       ) AS e(rid, exp_version, expected) ON e.rid = c.rule_id",
          "ORDER  BY verdict DESC, rule_id;",
          "",
          "-- 2b — history survived. EXPECTED: no rule lost a version.",
          "SELECT rule_id, count(*) AS versions, array_sort(collect_set(rule_version)) AS vs",
          f"FROM   {reg}",
          "GROUP  BY rule_id HAVING count(*) > 1 ORDER BY rule_id;",
          "",
          "-- 2c — THE ONE THAT MATTERS: the counts did not move.",
          "-- Each helper is executed against the real rows and diffed against the",
          f"-- number the Python evaluator produced. EXPECTED: {len(targets)} PASS.",
          "-- Two to read regardless of the verdict column — both must stay broken:",
          "--   SUBS_IMEI_NOT_NULL       200",
          "--   SUBS_BNFT_TXT_NOT_NULL   750  (shadow — measured, never raises)",
          ]
    sel = []
    for _, r in targets.iterrows():
        t = tbl.get(r.target_table, r.target_table)
        where = f" WHERE {r.scope_filter}" if pd.notna(r.scope_filter) and r.scope_filter else ""
        ev = last.loc[r.rule_id]
        sel.append(
            f"  SELECT {sql_str(r.rule_id):<28} AS rule_id,"
            f" count_if({r.rule_expr}) AS violations,"
            f" {int(ev.violation_count)} AS expected,"
            f" count(*) AS scanned,"
            f" {int(ev.rows_scanned)} AS exp_scanned"
            f"\n  FROM   {t}{where}")
    p += ["SELECT rule_id, violations, expected, scanned, exp_scanned,",
          "       CASE WHEN violations = expected AND scanned = exp_scanned",
          "            THEN 'PASS' ELSE 'FAIL' END AS verdict",
          "FROM (",
          "\n  UNION ALL\n".join(sel),
          ") ORDER BY verdict DESC, rule_id;",
          ""]

    (OUT / "migrate_fn_adoption.sql").write_text("\n".join(p) + "\n")
    print(f"wrote sql/out/migrate_fn_adoption.sql — {len(targets)} rules")
    for _, r in targets.iterrows():
        print(f"    {r.rule_id:26} -> v{int(r.rule_version)}  [{r.status}]")
    print("\nNOT RUN. Read steps 0a-0c before applying; there is no rollback.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
