#!/usr/bin/env python3
"""Generate the migration that registers the rules extracted from "DQ Queries".

    python3 sql/migrate_dq_queries.py --catalog workspace --schema dq_triage --prefix dq_

Writes sql/out/migrate_dq_queries.sql. Two parts, in order, then read-only checks.

PART 1 -- TWO BINDINGS. MID_NM joins CDE_CUST_NAME and CTCT_ID joins CDE_CUST_KEY, so
every new rule names an element that binds its column. A new cde_version per element,
bindings written from the FIXTURE with the seed's table-name rewrite applied -- the
lesson of migrate_cde_scope.py, where copying bindings forward lost one -- and every
other column carried forward from the version superseded.

PART 2 -- 34 RULES, ALL SHADOW, rule_version 1. Values from fixtures/out/, with the
two rewrites sql/seed.py applies: prod.customer.* to the mock tables, and dq.fn. to
the rendered helper prefix (rule_expr only; the scope filters are written longhand
for exactly that reason). promoted_by / promoted_at are NULL: a shadow rule has not
been promoted, and the DDL's CHECK says so.

The rules they may replace -- CTCT_PHN_FMT, CTCT_MOBL_FMT, CTCT_BRTH_PLAUSIBLE -- are
NOT touched. Retiring them is a separate migration, after promotion.

RE-RUNNABLE. Every INSERT is guarded: a rule_id already registered is skipped, and an
element version is skipped if its current version already binds the column. appendOnly
means a duplicate could never be removed, so a second run must be a no-op.

NOT RUN. There is no rollback -- reverting is another INSERT (status = 'retired').
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import pandas as pd

ROOT = pathlib.Path(__file__).parent.parent
FIX = ROOT / "fixtures" / "out"
OUT = pathlib.Path(__file__).parent / "out"
sys.path.insert(0, str(ROOT / "fixtures"))
sys.path.insert(0, str(pathlib.Path(__file__).parent))

import rules as fixture_rules  # noqa: E402
from migrate_cde_scope import (BINDING_FIELDS, CDE_COLUMNS, RULE_COLUMNS,  # noqa: E402
                               binding_lit, lit)

NEW_BINDINGS = {"CDE_CUST_NAME": "MID_NM", "CDE_CUST_KEY": "CTCT_ID"}


def build(catalog: str, schema: str, prefix: str, src_prefix: str = "dq_mock_",
          fn_prefix: str | None = None) -> tuple[list[str], list[tuple[str, str, str]]]:
    """Returns (file lines, [(label, kind, statement)]). kind is 'insert' or 'check'.

    The statement list is what tools explain: the notes carry semicolons, so
    splitting the written file on ';' would cut statements in half."""
    q = f"{catalog}.{schema}."
    fn_prefix = fn_prefix or f"{catalog}.{schema}.{prefix}fn_"
    cde = f"{q}{prefix}config_cde_registry"
    cde_cur = f"{q}{prefix}config_v_cde_registry_current"
    reg = f"{q}{prefix}config_rule_registry"
    reg_cur = f"{q}{prefix}config_v_rule_registry_current"
    cov = f"{q}{prefix}results_v_cde_coverage"
    rewrite = {"prod.customer.ctct_c": f"{q}{src_prefix}ctct_c",
               "prod.customer.subs_c": f"{q}{src_prefix}subs_c"}

    ids = [r.rule_id for r in fixture_rules.DQ_QUERIES_RULES]
    id_list = ", ".join(lit(i) for i in ids)
    cdes = pd.read_parquet(FIX / "config.cde_registry.parquet")
    cdes = cdes.sort_values("cde_version").groupby("cde_id").tail(1).set_index("cde_id")
    reg_fix = pd.read_parquet(FIX / "config.rule_registry.parquet")
    # VERSION 1, which is what this migration registers. Ten of these rules have
    # since moved onto helpers (sql/migrate_dq_fn.py) and their current version is 2;
    # reading the current one would register v2's expression under v1. The note is
    # the rule's own -- the fixture's v1 row carries the note explaining v2.
    reg_fix = reg_fix[reg_fix.rule_id.isin(ids) & (reg_fix.rule_version == 1)]
    reg_fix = reg_fix.set_index("rule_id").loc[ids].reset_index()
    reg_fix["note"] = [fixture_rules.BY_ID[i].note for i in reg_fix.rule_id]
    assert len(reg_fix) == len(ids) == 34, len(reg_fix)
    assert (reg_fix.status == "shadow").all() and (reg_fix.rule_version == 1).all()

    stmts: list[tuple[str, str, str]] = []
    lines = [
        "-- =====================================================================",
        "-- migrate_dq_queries.sql — GENERATED by sql/migrate_dq_queries.py. Do not edit.",
        f"-- target: {catalog}.{schema}, prefix {prefix}",
        "--",
        "-- Registers the 34 rules extracted from the workspace folder 'DQ Queries' on",
        "-- 2026-10-05, all in SHADOW, and binds MID_NM and CTCT_ID so each names an",
        "-- element. Touches no existing rule. Every INSERT is guarded: re-running is a",
        "-- no-op. See the generator's docstring.",
        "-- =====================================================================",
    ]

    def add(label: str, kind: str, sql: str, comment: list[str] | None = None) -> None:
        stmts.append((label, kind, sql))
        lines.extend(["", *(comment or []), sql + ";"])

    lines += ["", "-- Step 0 — where is this workspace? EXPECTED before: 0, and the bindings",
              "-- below without MID_NM / CTCT_ID. After: 34, and both present."]
    add("0a", "check", f"SELECT COUNT(DISTINCT rule_id) AS already_registered\n"
                       f"FROM   {reg}\nWHERE  rule_id IN ({id_list})")
    add("0b", "check", f"SELECT cde_id, cde_version,\n"
                       f"       transform(bindings, b -> b.target_column) AS bound_columns\n"
                       f"FROM   {cde_cur}\nWHERE  cde_id IN ("
                       + ", ".join(lit(c) for c in NEW_BINDINGS) + ")")

    lines += ["", "-- =====================================================================",
              "-- Part 1 — two bindings, one new cde_version each",
              "-- ====================================================================="]
    for cde_id, col in NEW_BINDINGS.items():
        r = cdes.loc[cde_id]
        bound = [b["target_column"] for b in r.bindings]
        assert col in bound, (cde_id, col, bound)
        note = (f"Binds {col}, so the rules extracted from the workspace folder 'DQ Queries' "
                f"on 2026-10-05 can name this element. Bindings now {', '.join(bound)}. "
                f"Nothing else about the element changed.")
        cols = [c for c in CDE_COLUMNS]
        select = []
        for c in cols:
            if c == "cde_version":
                select.append("cde_version + 1")
            elif c == "bindings":
                select.append("array(" + ", ".join(binding_lit(b, rewrite) for b in r.bindings) + ")")
            elif c in ("effective_from", "registered_at"):
                select.append("current_timestamp()")
            elif c == "registered_by":
                select.append("current_user()")
            elif c == "note":
                select.append(lit(note))
            else:
                select.append(c)
        add(f"cde:{cde_id}", "insert",
            f"INSERT INTO {cde} ({', '.join(cols)})\n"
            f"SELECT {', '.join(select)}\n"
            f"FROM   {cde}\n"
            f"WHERE  cde_id = {lit(cde_id)}\n"
            f"  AND  cde_version = (SELECT max(cde_version) FROM {cde} WHERE cde_id = {lit(cde_id)})\n"
            f"  AND  NOT array_contains(transform(bindings, b -> b.target_column), {lit(col)})",
            [f"-- {cde_id}  + {col}   (skipped if already bound)"])

    lines += ["", "-- =====================================================================",
              f"-- Part 2 — {len(ids)} rules, rule_version 1, status shadow",
              "-- ====================================================================="]
    for _, r in reg_fix.iterrows():
        vals = []
        for c in RULE_COLUMNS:
            v = r[c]
            if hasattr(v, "item"):
                v = v.item()
            if isinstance(v, float) and pd.isna(v) and c != "fail_threshold_pct":
                v = None    # a NULL string column comes back from parquet as NaN
            if c == "target_table":
                v = rewrite.get(v, v)
            elif c == "rule_expr":
                v = v.replace("dq.fn.", fn_prefix)
            elif c == "scope_filter" and v is not None:
                assert "dq.fn." not in v, (r.rule_id, v)
            if c in ("effective_from", "created_at"):
                vals.append("current_timestamp()")
            elif c == "created_by":
                vals.append("current_user()")
            elif c in ("promoted_by", "promoted_at"):
                vals.append("CAST(NULL AS TIMESTAMP)" if c == "promoted_at" else "CAST(NULL AS STRING)")
            elif c == "fail_threshold_pct":
                vals.append(f"CAST({float(v)} AS DOUBLE)")
            elif c == "rule_version":
                vals.append(f"{int(v)}")
            else:
                vals.append(lit(v) if v is not None else "CAST(NULL AS STRING)")
        add(f"rule:{r.rule_id}", "insert",
            f"INSERT INTO {reg} ({', '.join(RULE_COLUMNS)})\n"
            f"SELECT " + ",\n       ".join(vals) + "\n"
            f"WHERE  NOT EXISTS (SELECT 1 FROM {reg} WHERE rule_id = {lit(r.rule_id)})",
            [f"-- {r.rule_id}  [{r.rule_type}, {r.severity}] -> {r.cde_id}"])

    lines += ["", "-- =====================================================================",
              "-- Part 3 — verification, read-only",
              "-- ====================================================================="]
    add("3a", "check",
        f"SELECT status, COUNT(*) AS rules\nFROM   {reg_cur}\nWHERE  rule_id IN ({id_list})\n"
        f"GROUP  BY status",
        ["-- 3a — EXPECTED: one row, shadow 34."])
    add("3b", "check",
        "SELECT r.rule_id, r.cde_id, r.target_column\n"
        f"FROM   {reg_cur} r\n"
        "LEFT JOIN (SELECT c.cde_id, b.target_table, b.target_column\n"
        f"           FROM {cde_cur} c LATERAL VIEW explode(c.bindings) x AS b\n"
        "           WHERE c.status = 'registered' AND b.binding_status = 'bound') e\n"
        "  ON  e.cde_id = r.cde_id AND e.target_table = r.target_table\n"
        "  AND e.target_column = r.target_column\n"
        f"WHERE r.rule_id IN ({id_list}) AND e.cde_id IS NULL",
        ["-- 3b — EXPECTED: zero rows. Every new rule names an element that binds its column."])
    add("3c", "check",
        f"SELECT rule_id FROM {reg_cur}\n"
        f"WHERE  rule_id IN ({id_list}) AND (rule_expr LIKE '%dq.fn.%' OR scope_filter LIKE '%dq.fn.%'\n"
        "       OR target_table LIKE 'prod.%')",
        ["-- 3c — EXPECTED: zero rows. Nothing left pointing at a canonical name."])
    add("3d", "check",
        f"SELECT coverage_gap, COUNT(*) AS bindings FROM {cov} GROUP BY coverage_gap ORDER BY 1",
        ["-- 3d — coverage after. Shadow rules do not count, so only the two new bindings",
         "-- move it: CTCT_ID by the orphan check tagged on its element, MID_NM by name",
         "-- agreement. Compare with the run before."])
    return lines, stmts


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", default="workspace")
    ap.add_argument("--schema", default="dq_triage")
    ap.add_argument("--prefix", default="dq_")
    ap.add_argument("--src-prefix", default="dq_mock_")
    ap.add_argument("--fn-prefix", default=None,
                    help="Replaces `dq.fn.` in rule_expr. Default <catalog>.<schema>.<prefix>fn_, "
                         "what render.py produces; must match sql/seed.py.")
    a = ap.parse_args()
    lines, stmts = build(a.catalog, a.schema, a.prefix, a.src_prefix, a.fn_prefix)
    (OUT / "migrate_dq_queries.sql").write_text("\n".join(lines) + "\n")
    n = sum(k == "insert" for _, k, _ in stmts)
    print(f"wrote sql/out/migrate_dq_queries.sql — {n} guarded INSERTs "
          f"(2 element versions, {n - 2} rules), {len(stmts) - n} read-only checks")
    print("\nNOT RUN.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
