#!/usr/bin/env python3
"""Generate the migration that moves ten "DQ Queries" rules onto three new helpers.

    python3 sql/migrate_dq_fn.py --catalog workspace --schema dq_triage --prefix dq_

Writes sql/out/migrate_dq_fn.sql. Run AFTER migrate_dq_queries.sql.

PART 1 -- THREE FUNCTIONS. au_phone_digits_v1, is_phone_placeholder_v1 and
is_name_placeholder_v1, the bodies taken verbatim from the rendered
sql/out/08_functions.sql. CREATE FUNCTION IF NOT EXISTS, never CREATE OR REPLACE: the
header of 12_functions.sql calls OR REPLACE on a referenced function a control
failure, and this file must not be able to re-issue one. The four existing helpers
are not touched.

PART 2 -- EQUIVALENCE, READ-ONLY. For every rule, v1 (what is registered) and v2
(what will be) counted side by side on the mock table. EXPECTED: identical, every row.
Stop if not.

PART 3 -- TEN rule_versions. v2 of each rule, everything carried forward from v1
except rule_expr, the phone rules' scope_filter (a shorter longhand -- the scope
cannot call a helper) and the note. Guarded on the rule still being at v1, so a
second run is a no-op. Status stays shadow and promoted_by stays NULL.

NOT RUN by generating. There is no rollback -- reverting is a v3 carrying v1 back.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).parent.parent
OUT = pathlib.Path(__file__).parent / "out"
sys.path.insert(0, str(ROOT / "fixtures"))
sys.path.insert(0, str(pathlib.Path(__file__).parent))

import rules as fixture_rules  # noqa: E402
from migrate_cde_scope import RULE_COLUMNS, lit  # noqa: E402

NEW_FUNCTIONS = ["au_phone_digits_v1", "is_phone_placeholder_v1", "is_name_placeholder_v1"]


def _function_bodies(rendered: str, fn_prefix: str) -> dict[str, str]:
    out = {}
    for name in NEW_FUNCTIONS:
        m = re.search(r"CREATE OR REPLACE FUNCTION " + re.escape(fn_prefix + name)
                      + r"\(.*?;\n", rendered, flags=re.S)
        if not m:
            raise SystemExit(f"{name} not found in sql/out/08_functions.sql -- re-render first")
        out[name] = m.group(0).rstrip().rstrip(";").replace(
            "CREATE OR REPLACE FUNCTION", "CREATE FUNCTION IF NOT EXISTS", 1)
    return out


def build(catalog: str, schema: str, prefix: str, src_prefix: str = "dq_mock_",
          fn_prefix: str | None = None) -> tuple[list[str], list[tuple[str, str, str]]]:
    """Returns (file lines, [(label, kind, statement)]); kind is create/check/insert."""
    q = f"{catalog}.{schema}."
    fn_prefix = fn_prefix or f"{catalog}.{schema}.{prefix}fn_"
    reg = f"{q}{prefix}config_rule_registry"
    reg_cur = f"{q}{prefix}config_v_rule_registry_current"
    table = f"{q}{src_prefix}ctct_c"
    moved = [r for r in fixture_rules.DQ_QUERIES_RULES if r.rule_version == 2]
    assert len(moved) == 10, [r.rule_id for r in moved]
    ids = ", ".join(lit(r.rule_id) for r in moved)
    fx = lambda s: s.replace("dq.fn.", fn_prefix) if s else s  # noqa: E731

    bodies = _function_bodies((OUT / "08_functions.sql").read_text(), fn_prefix)
    stmts: list[tuple[str, str, str]] = []
    lines = [
        "-- =====================================================================",
        "-- migrate_dq_fn.sql — GENERATED by sql/migrate_dq_fn.py. Do not edit.",
        f"-- target: {catalog}.{schema}, prefix {prefix}",
        "--",
        "-- Three new helpers, and ten 'DQ Queries' rules moved onto them as v2.",
        "-- Run after migrate_dq_queries.sql. Part 2 is read-only and must show",
        "-- identical counts before Part 3 is run. Re-running is a no-op.",
        "-- =====================================================================",
    ]

    def add(label, kind, sql, comment=None):
        stmts.append((label, kind, sql))
        lines.extend(["", *(comment or []), sql + ";"])

    lines += ["", "-- Step 0 — EXPECTED before: no new function, all ten rules at v1."]
    add("0a", "check",
        "SELECT routine_name FROM information_schema.routines\n"
        f"WHERE  routine_schema = '{schema}'\n"
        f"  AND  routine_name IN (" + ", ".join(f"'{prefix}fn_{n}'" for n in NEW_FUNCTIONS) + ")")
    add("0b", "check", f"SELECT rule_version, COUNT(*) AS rules FROM {reg_cur}\n"
                       f"WHERE  rule_id IN ({ids}) GROUP BY rule_version")

    lines += ["", "-- =====================================================================",
              "-- Part 1 — three functions. IF NOT EXISTS: never replaces a referenced helper.",
              "-- ====================================================================="]
    for name in NEW_FUNCTIONS:
        add(f"fn:{name}", "create", bodies[name])

    lines += ["", "-- =====================================================================",
              "-- Part 2 — equivalence, read-only. EXPECTED: v1 = v2 on every row.",
              "-- ====================================================================="]
    for r in moved:
        old = r.superseded[0]
        o_expr, o_scope = fx(old["rule_expr"]), old.get("scope_filter", r.scope_filter)
        n_expr, n_scope = fx(r.rule_expr), r.scope_filter
        if "OVER (PARTITION BY" in r.rule_expr:
            sql = (f"SELECT {lit(r.rule_id)} AS rule_id,\n"
                   f"       (SELECT count_if(d) FROM (SELECT {o_expr} AS d FROM {table} WHERE {o_scope})) AS v1,\n"
                   f"       (SELECT count_if(d) FROM (SELECT {n_expr} AS d FROM {table} WHERE {n_scope})) AS v2")
        else:
            sql = (f"SELECT {lit(r.rule_id)} AS rule_id,\n"
                   f"       count_if(({o_scope}) AND ({o_expr})) AS v1,\n"
                   f"       count_if(({n_scope}) AND ({n_expr})) AS v2,\n"
                   f"       count_if({o_scope}) AS scope_v1, count_if({n_scope}) AS scope_v2\n"
                   f"FROM   {table}")
        add(f"eq:{r.rule_id}", "check", sql)

    lines += ["", "-- =====================================================================",
              "-- Part 3 — ten rule_versions, guarded on the rule still being at v1",
              "-- ====================================================================="]
    for r in moved:
        select = []
        for c in RULE_COLUMNS:
            if c == "rule_version":
                select.append("rule_version + 1")
            elif c == "rule_expr":
                select.append(lit(fx(r.rule_expr)))
            elif c == "scope_filter":
                select.append(lit(r.scope_filter))
            elif c in ("effective_from", "created_at"):
                select.append("current_timestamp()")
            elif c == "created_by":
                select.append("current_user()")
            elif c == "note":
                select.append(lit(r.superseded[0]["note"]))
            else:
                select.append(c)
        add(f"rule:{r.rule_id}", "insert",
            f"INSERT INTO {reg} ({', '.join(RULE_COLUMNS)})\n"
            f"SELECT {', '.join(select)}\n"
            f"FROM   {reg}\n"
            f"WHERE  rule_id = {lit(r.rule_id)}\n"
            f"  AND  rule_version = 1\n"
            f"  AND  NOT EXISTS (SELECT 1 FROM {reg} WHERE rule_id = {lit(r.rule_id)} AND rule_version > 1)",
            [f"-- {r.rule_id}  v1 -> v2"])

    lines += ["", "-- =====================================================================",
              "-- Part 4 — verification, read-only",
              "-- ====================================================================="]
    add("4a", "check", f"SELECT rule_version, status, COUNT(*) AS rules FROM {reg_cur}\n"
                       f"WHERE  rule_id IN ({ids}) GROUP BY rule_version, status",
        ["-- 4a — EXPECTED: one row, version 2, shadow, 10."])
    add("4b", "check", f"SELECT rule_id FROM {reg_cur}\nWHERE  rule_id IN ({ids})\n"
                       "  AND  (rule_expr LIKE '%CASE WHEN%' OR rule_expr LIKE '%NOT PROVIDED%'\n"
                       "       OR rule_expr LIKE '%dq.fn.%' OR promoted_by IS NOT NULL)",
        ["-- 4b — EXPECTED: zero rows. No longhand left, no canonical name, nothing promoted."])
    return lines, stmts


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", default="workspace")
    ap.add_argument("--schema", default="dq_triage")
    ap.add_argument("--prefix", default="dq_")
    ap.add_argument("--src-prefix", default="dq_mock_")
    ap.add_argument("--fn-prefix", default=None)
    a = ap.parse_args()
    lines, stmts = build(a.catalog, a.schema, a.prefix, a.src_prefix, a.fn_prefix)
    (OUT / "migrate_dq_fn.sql").write_text("\n".join(lines) + "\n")
    kinds = [k for _, k, _ in stmts]
    print(f"wrote sql/out/migrate_dq_fn.sql — {kinds.count('create')} functions, "
          f"{kinds.count('insert')} guarded rule versions, {kinds.count('check')} read-only checks")
    print("\nNOT RUN.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
