#!/usr/bin/env python3
"""Generate the migration that adds config.rule_registry.join_sql and fills it.

    python3 sql/migrate_join_sql.py --catalog workspace --schema dq_triage --prefix dq_

Writes sql/out/migrate_join_sql.sql. Two parts, and the second is the awkward one.

PART 1 -- ADD THE COLUMN. `ALTER TABLE ... ADD COLUMN` is a schema change, not a data
change, so `delta.appendOnly` permits it. Every existing row reads NULL, which is
correct for the 31 single-table rules and is exactly what the runner treats as "this
cross-table rule cannot be executed".

PART 2 -- FILL IT FOR THE THREE CROSS-TABLE RULES, AND WHY THAT IS A NEW VERSION.
The obvious move is UPDATE ... SET join_sql = ... on three rows. appendOnly blocks it,
and that is the property working rather than getting in the way: the register's claim is
that nothing here is ever rewritten in place, and a one-off exception for a backfill is
still an exception.

So each of the three gets a new rule_version. Be clear-eyed that this is a version
number carrying no behaviour change -- the rule is the same rule, the join was always
this join, and the only thing that changed is that a column now exists to record it.
The note on each row says so, because a reader finding v2 will otherwise look for the
difference and not find one.

THE ALTERNATIVE, stated so the choice is visible: unset appendOnly, UPDATE the three
rows, set it again. Fewer rows, no misleading version, and it means the audit table was
editable for the duration. That is a governance decision, not a technical one, and it is
not the default this file takes.

NOT RUN. Read it before applying. There is no rollback -- reverting is another INSERT.
"""

from __future__ import annotations

import argparse
import pathlib

import pandas as pd

ROOT = pathlib.Path(__file__).parent.parent
FIX = ROOT / "fixtures" / "out"
OUT = pathlib.Path(__file__).parent / "out"

COMMENT = ("For a cross-table rule: the FROM-clause body the check runner reads instead "
           "of target_table -- the joined table expression with its aliases and ON "
           "condition. NOT a full SELECT: rule_expr stays the predicate and references "
           "these aliases, so the predicate is stored once. NULL for every single-table "
           "rule.")


def lit(v: str) -> str:
    return "'" + str(v).replace("\\", "\\\\").replace("'", "\\'") + "'"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", default="workspace")
    ap.add_argument("--schema", default="dq_triage")
    ap.add_argument("--prefix", default="dq_")
    ap.add_argument("--src-prefix", default="dq_mock_")
    a = ap.parse_args()

    q = f"{a.catalog}.{a.schema}."
    reg = f"{q}{a.prefix}config_rule_registry"
    rewrite = {"prod.customer.ctct_c": f"{q}{a.src_prefix}ctct_c",
               "prod.customer.subs_c": f"{q}{a.src_prefix}subs_c"}

    df = pd.read_parquet(FIX / "config.rule_registry.parquet")
    cur = df.sort_values("rule_version").groupby("rule_id", as_index=False).tail(1)
    xrefs = cur[cur["join_sql"].notna()].sort_values("rule_id")

    p = [
        "-- =====================================================================",
        "-- migrate_join_sql.sql — GENERATED by sql/migrate_join_sql.py. Do not edit.",
        f"-- target: {a.catalog}.{a.schema}, prefix {a.prefix}",
        "--",
        "-- Adds config.rule_registry.join_sql and fills it for the cross-table rules.",
        "-- Part 1 is a schema change and appendOnly permits it. Part 2 is an INSERT per",
        "-- rule, NOT an UPDATE, because appendOnly blocks one and the audit claim is",
        "-- that nothing here is rewritten in place. See sql/migrate_join_sql.py for the",
        "-- alternative and why it was not taken.",
        "-- =====================================================================",
        "",
        "-- ---------------------------------------------------------------------",
        "-- Step 0 — has the column already been added?",
        "-- EXPECTED: zero rows before, one row after.",
        "-- ---------------------------------------------------------------------",
        "SELECT column_name, data_type",
        f"FROM   {a.catalog}.information_schema.columns",
        f"WHERE  table_schema = '{a.schema}'",
        f"  AND  table_name = '{a.prefix}config_rule_registry'",
        "  AND  column_name = 'join_sql';",
        "",
        "-- ---------------------------------------------------------------------",
        "-- Step 1 — add the column. Existing rows read NULL, which is correct for",
        "-- every single-table rule and is what the runner reads as 'this cross-table",
        "-- rule has no join and cannot be executed'.",
        "-- ---------------------------------------------------------------------",
        f"ALTER TABLE {reg}",
        f"  ADD COLUMN join_sql STRING COMMENT {lit(COMMENT)};",
        "",
        "-- =====================================================================",
        f"-- Step 2 — fill it for the {len(xrefs)} cross-table rules",
        "--",
        "-- A new rule_version carrying NO behaviour change. The rule is the same rule",
        "-- and the join was always this join; the only thing that changed is that a",
        "-- column now exists to hold it. Each note says so.",
        "-- =====================================================================",
    ]

    for _, r in xrefs.iterrows():
        j = r.join_sql
        for k, v in rewrite.items():
            j = j.replace(k, v)
        note = (f"v{int(r.rule_version) + 1}: join_sql populated. NO behaviour change -- "
                f"this is the same rule with the same join, which until 2026-09-28 had "
                f"no column in config.rule_registry to live in and was carried in "
                f"fixtures/rules.py instead. A new version rather than an UPDATE because "
                f"the registry is appendOnly and that is the point of it. Do not look for "
                f"a difference in what this version measures.")
        p += [
            "",
            f"-- {r.rule_id}  -> v{int(r.rule_version) + 1}   [{r.status}]",
            f"--   join_sql: {j}",
            # An EXPLICIT column list, not INSERT ... SELECT. `ALTER TABLE ADD
            # COLUMN` appends join_sql at the END of the table while sql/ddl/ declares
            # it after scope_filter, so a positional INSERT would line every column up
            # against the wrong one on a migrated table and silently load garbage. Named
            # columns make the statement work whichever order the table is in.
            f"INSERT INTO {reg} (",
            "  rule_id, rule_version, rule_name, target_table, target_column, cde_id,",
            "  rule_type, rule_expr, scope_filter, join_sql, fail_threshold_pct,",
            "  severity, business_domain, owner_group, source_layer, status,",
            "  effective_from, created_by, created_at, promoted_by, promoted_at, note",
            ")",
            "SELECT",
            "  rule_id,",
            "  rule_version + 1                    AS rule_version,",
            "  rule_name, target_table, target_column, cde_id, rule_type, rule_expr,",
            "  scope_filter,",
            f"  {lit(j)} AS join_sql,",
            "  fail_threshold_pct, severity, business_domain, owner_group, source_layer,",
            "  status,",
            "  current_timestamp()                 AS effective_from,",
            "  current_user()                      AS created_by,",
            "  current_timestamp()                 AS created_at,",
            "  promoted_by, promoted_at,",
            f"  {lit(note)} AS note",
            f"FROM   {reg}",
            f"WHERE  rule_id = {lit(r.rule_id)}",
            f"  AND  rule_version = (SELECT max(rule_version) FROM {reg}",
            f"                       WHERE rule_id = {lit(r.rule_id)});",
        ]

    p += [
        "",
        "-- =====================================================================",
        "-- Step 3 — verification, read-only",
        "-- =====================================================================",
        "",
        f"-- 3a — EXPECTED: {len(xrefs)} rows, every join_sql non-null.",
        "SELECT rule_id, rule_version, target_table, target_column, join_sql",
        f"FROM   {q}{a.prefix}config_v_rule_registry_current",
        "WHERE  join_sql IS NOT NULL ORDER BY rule_id;",
        "",
        "-- 3b — EXPECTED: zero rows. A cross-table rule is one with no target_column;",
        "-- after this migration every one of them must carry a join.",
        "SELECT rule_id, rule_version, status",
        f"FROM   {q}{a.prefix}config_v_rule_registry_current",
        "WHERE  target_column IS NULL AND join_sql IS NULL AND status <> 'retired'",
        "ORDER  BY rule_id;",
        "",
    ]
    (OUT / "migrate_join_sql.sql").write_text("\n".join(p) + "\n")
    print(f"wrote sql/out/migrate_join_sql.sql — 1 ALTER + {len(xrefs)} INSERTs")
    for _, r in xrefs.iterrows():
        print(f"    {r.rule_id:26} -> v{int(r.rule_version) + 1}")
    print("\nNOT RUN.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
