r"""Emit all-STRING DDL for the two mock source tables.

    python3 sql/mocktables.py

Writes sql/out/mocktables.sql. Reads only the CSV headers — no data is read, and
none is embedded in the output.

WHY ALL STRING, AND WHY THIS SCRIPT EXISTS

The first sandpit load used type inference and four rules failed the fixture diff.
All four were the load, not the rules:

  CTCT_MOBL_FMT            MOBL_NO inferred numeric; '0470000001' -> 470000001,
                           leading zero gone, 982 false violations
  SUBS_ACTV_TS_CONSISTENT  INIT_ACTV_TS holds the literal 'not-a-timestamp' in 10
                           rows. Parsed as TIMESTAMP it becomes NULL, x <> NULL is
                           NULL, and count_if drops it: 10 real defects -> 0
  XREF_OPEN_TS_AGREEMENT   same mechanism, 11 rows
  XREF_NAME_AGREEMENT      2 rows carry a blank name. '' <> 'John' is TRUE;
                           NULL <> 'John' is NULL

fixtures/build_fixtures.py reads both CSVs as `dtype=str, keep_default_na=False` —
every column a string, every blank an empty string, never NULL. These tables have to
match that or the diff compares two different datasets.

THE POINT THAT OUTLIVES THE SANDPIT

These are bronze tables. Bronze lands text so that bad values survive to be
DETECTED. A load that parses INIT_ACTV_TS to a timestamp silently discards
'not-a-timestamp' before any rule runs — the defect is gone, and the check runner
reports a clean column. A typed load is a data quality filter, and an undocumented
one. Whatever eventually writes the real bronze tables should land these columns as
STRING for the same reason.
"""

from __future__ import annotations

import argparse
import csv
import pathlib
import sys

OUT = pathlib.Path(__file__).parent / "out"

SOURCES = {
    "ctct_c": "mock_ctct_c_1000 (1).csv",
    "subs_c": "mock_subs_c_1000 (1).csv",
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", default="sdpt_data_trnf")
    ap.add_argument("--schema", default="udp_brnz")
    ap.add_argument("--src-prefix", default="dq_mock_")
    ap.add_argument("--csv-dir", default=str(pathlib.Path.home() / "Downloads"))
    ap.add_argument("--volume", default="/Volumes/<catalog>/<schema>/<volume>",
                    help="where the CSVs will sit for COPY INTO")
    a = ap.parse_args()

    src = pathlib.Path(a.csv_dir)
    parts = [
        "-- =====================================================================",
        "-- mocktables.sql — GENERATED by sql/mocktables.py. Do not edit.",
        f"-- target: {a.catalog}.{a.schema}",
        "--",
        "-- EVERY COLUMN IS STRING. That is not laziness — see the script header.",
        "-- The fixture reads these CSVs as dtype=str with blanks kept as empty",
        "-- strings, and the diff is only meaningful against the same shape.",
        "--",
        "-- Run order: DROP, CREATE, then EITHER COPY INTO (if the CSVs are in a",
        "-- volume) OR re-upload through the UI into the table this creates.",
        "-- =====================================================================",
        "",
    ]

    for short, fname in SOURCES.items():
        p = src / fname
        if not p.exists():
            print(f"missing CSV: {p}", file=sys.stderr)
            return 1
        with p.open(newline="") as fh:
            cols = next(csv.reader(fh))
        tgt = f"{a.catalog}.{a.schema}.{a.src_prefix}{short}"
        width = max(len(c) for c in cols)
        body = ",\n".join(f"  {c:<{width}} STRING" for c in cols)
        parts += [
            f"-- ---------- {tgt}  ({len(cols)} columns) ----------",
            f"DROP TABLE IF EXISTS {tgt};",
            "",
            f"CREATE TABLE {tgt} (",
            body,
            ")",
            "USING DELTA",
            f"COMMENT 'Mock source stand-in for prod.customer.{short}. All STRING by "
            "design: a typed load silently nulls the bad values the rules exist to find.';",
            "",
            "-- Option A — CSV already in a volume:",
            f"-- COPY INTO {tgt}",
            f"--   FROM '{a.volume}/{fname}'",
            "--   FILEFORMAT = CSV",
            "--   FORMAT_OPTIONS ('header' = 'true',",
            "--                   'inferSchema' = 'false',",
            "--                   'nullValue' = '\\u0000')   -- keeps blanks as '', not NULL",
            "--   COPY_OPTIONS ('mergeSchema' = 'false');",
            "",
            "-- Option B — upload through the UI, targeting this existing table so the",
            "-- STRING types are kept. Blanks will land as NULL, which leaves",
            "-- XREF_NAME_AGREEMENT reading 0 instead of 2. Everything else matches.",
            "",
        ]

    (OUT / "mocktables.sql").write_text("\n".join(parts) + "\n")
    print("wrote sql/out/mocktables.sql")
    for short in SOURCES:
        print(f"    {a.catalog}.{a.schema}.{a.src_prefix}{short}")
    print("\nthen re-run sql/out/checkrun.sql — expect 34 PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
