#!/usr/bin/env python3
"""Render ddl/*.sql for a sandpit that has no catalog or grant privileges.

    python3 sql/render.py                    # defaults to the sdpt_data_trnf sandpit
    python3 sql/render.py --catalog c --schema s --prefix dq_

`sql/ddl/` stays the source of truth and keeps its {catalog} placeholders — this
writes a disposable, runnable copy to `sql/out/`, the same way `fixtures/out/` is
generated from `build_fixtures.py`. Do not edit `sql/out/` by hand; re-render it.

WHAT THIS CHANGES, AND WHY

The DDL assumes a catalog of its own with two schemas. A sandpit gives you one
schema in someone else's catalog, so the schema split becomes a name prefix:

    {catalog}.config.rule_registry   ->  <cat>.<schema>.dq_config_rule_registry
    {catalog}.results.check_run      ->  <cat>.<schema>.dq_results_check_run
    {catalog}.fn.is_blank_v1         ->  <cat>.<schema>.dq_fn_is_blank_v1

config_ / results_ / fn_ are kept rather than flattened away. They cost nine
characters and they preserve, in the only place left to preserve it, the split that
`07_grants.sql` argues is what makes the grant model expressible at all. They also
keep these tables from colliding with anything else in a shared bronze schema.

WHAT THIS DROPS

  00_schemas.sql   the schema already exists and you cannot create a catalog
  07_grants.sql    you cannot grant. THIS IS THE CONTROL — see sql/VERIFY.md on what
                   a green sandpit run does and does not prove
  12, partially    its CREATE SCHEMA and its grants block; the four functions remain

Nothing else is altered. Every column, constraint, comment and view body is
byte-identical to `sql/ddl/` apart from the object names.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

DDL = pathlib.Path(__file__).parent / "ddl"
OUT = pathlib.Path(__file__).parent / "out"

SKIP = {
    "00_schemas.sql": "the schema already exists; CREATE CATALOG needs privileges you do not have",
    "07_grants.sql": "you cannot issue grants. This file is the control claim — see VERIFY.md",
}

# Views read tables, so they run last. 12 before them: nothing depends on it, but a
# rule referencing a missing function is a worse failure than a redundant one.
ORDER = ["01", "02", "03", "04", "05", "06", "09", "10", "12", "08", "11"]

HEADER = """-- GENERATED by sql/render.py — do not edit, re-render.
--   source:  sql/ddl/{src}
--   target:  {cat}.{sch}  (prefix {pre})
--
-- Comments below still say {{catalog}} and still describe two schemas. They are the
-- original text, kept so this file can be read against its source. The STATEMENTS
-- are rendered for the sandpit.
"""


def render(text: str, cat: str, sch: str, pre: str) -> str:
    q = f"{cat}.{sch}.{pre}"
    for schema in ("config", "results", "fn"):
        text = text.replace("{catalog}." + schema + ".", q + schema + "_")
    return text


def strip_12(text: str) -> str:
    """Remove the fn-schema creation and the grants block; keep the four functions."""
    text = re.sub(
        r"CREATE SCHEMA IF NOT EXISTS \{catalog\}\.fn\b.*?;\n",
        "-- (CREATE SCHEMA dropped by render.py — the sandpit schema already exists)\n",
        text,
        flags=re.S,
    )
    marker = "-- Grants\n"
    i = text.find(marker)
    if i == -1:
        raise SystemExit("render.py: could not find the Grants block in 12_functions.sql")
    divider = text.rfind("-- ---", 0, i)
    return text[:divider] + (
        "-- (Grants block dropped by render.py — you cannot grant in a sandpit.\n"
        "--  Keep ownership of these functions with whoever owns the schema, and see\n"
        "--  the _v1 immutability note in the header above.)\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", default="sdpt_data_trnf")
    ap.add_argument("--schema", default="udp_brnz")
    ap.add_argument("--prefix", default="dq_")
    a = ap.parse_args()

    OUT.mkdir(exist_ok=True)
    for stale in OUT.glob("*.sql"):
        stale.unlink()

    written, skipped = [], []
    for src in sorted(DDL.glob("*.sql")):
        if src.name in SKIP:
            skipped.append((src.name, SKIP[src.name]))
            continue
        text = src.read_text()
        if src.name.startswith("12"):
            text = strip_12(text)
        body = HEADER.format(src=src.name, cat=a.catalog, sch=a.schema, pre=a.prefix) + "\n" + \
            render(text, a.catalog, a.schema, a.prefix)

        seq = f"{ORDER.index(src.name[:2]):02d}"
        dst = OUT / f"{seq}_{src.name[3:]}"
        dst.write_text(body)
        written.append(dst.name)

    # Anything left is a placeholder we did not handle.
    leaks = []
    for f in OUT.glob("*.sql"):
        for n, line in enumerate(f.read_text().splitlines(), 1):
            if "{" in line and re.search(r"\{[a-z_]+\}", line) and not line.lstrip().startswith("--"):
                leaks.append(f"{f.name}:{n}: {line.strip()}")

    # One concatenated file for pasting into a SQL editor. Banners are numbered so a
    # failure is locatable without diffing against the per-file output.
    parts = [
        "-- =====================================================================\n"
        "-- ALL.sql — GENERATED by sql/render.py. Do not edit; re-render.\n"
        f"-- target: {a.catalog}.{a.schema}, prefix {a.prefix}\n"
        "--\n"
        f"-- {len(written)} files concatenated in run order. Views are last because they\n"
        "-- read the tables above them.\n"
        "--\n"
        "-- RUN ONCE. ALTER TABLE ... ADD CONSTRAINT is not idempotent: a second pass\n"
        "-- fails with \"constraint already exists\" on every one of the 23. If this stops\n"
        "-- partway, fix the one statement and continue from that banner — do not restart.\n"
        "--\n"
        "-- Expected when complete: 8 tables, 5 views, 4 functions, 23 CHECK constraints.\n"
        "-- Verify with sql/VERIFY.md steps 3-8. Step 9 (grants) is not available here.\n"
        "-- ====================================================================="
    ]
    for n, name in enumerate(sorted(written), 1):
        parts.append(
            f"\n\n-- =====================================================================\n"
            f"-- [{n}/{len(written)}]  {name}\n"
            f"-- =====================================================================\n"
        )
        parts.append((OUT / name).read_text())
    (OUT / "ALL.sql").write_text("".join(parts))

    print(f"rendered {len(written)} files to sql/out/ in run order:")
    for w in sorted(written):
        print(f"    {w}")
    print("\nskipped:")
    for name, why in skipped:
        print(f"    {name:22} {why}")
    if leaks:
        print("\nUNSUBSTITUTED PLACEHOLDERS — these will not run:")
        for l in leaks:
            print(f"    {l}")
        return 1
    print(f"\ntarget: {a.catalog}.{a.schema}, prefix {a.prefix}")
    print("no unsubstituted placeholders in any statement")
    print(f"\nalso wrote sql/out/ALL.sql — all {len(written)} files concatenated, for pasting")
    return 0


if __name__ == "__main__":
    sys.exit(main())
