#!/usr/bin/env python3
r"""Generate INSERT statements seeding the three config tables from the fixture.

    python3 sql/seed.py                    # defaults to the sdpt_data_trnf sandpit
    python3 sql/seed.py --catalog c --schema s --prefix dq_ --src-prefix dq_mock_

Writes sql/out/seed.sql. Generated and gitignored, like render.py's output — the
fixture Parquet in fixtures/out/ is the source, and it is itself generated from the
pilot CSVs. Do not edit seed.sql by hand.

Seeds 51 rows: 35 rule_registry, 6 playbook, 10 cde_registry. Nothing in results.*
is seeded — check_run is what the runner is supposed to produce, and seeding it
would defeat the point of Stage 2.

THE REWRITE THIS EXISTS FOR

config.rule_registry.target_table is baked as `prod.customer.ctct_c`, and the same
names appear inside every cde_registry bindings entry. Loaded verbatim, every rule
points at a catalog that does not exist. Both are rewritten here:

    prod.customer.ctct_c  ->  <cat>.<schema>.<src_prefix>ctct_c
    prod.customer.subs_c  ->  <cat>.<schema>.<src_prefix>subs_c

That the registry stores fully-qualified names is a real portability problem, not a
fixture artefact. It is worth recording as a design question rather than solving
here with a placeholder nobody agreed to.

BACKSLASHES — READ THIS BEFORE CHANGING sql_lit()

rule_expr values already hold DOUBLED backslashes: the stored value is
`^[^@\\s.]+...`, which is the Spark SQL string-literal form of the regex `\s`. The
check runner reads that value and interpolates it into SQL, where it is parsed a
second time back down to `\s`.

So writing it into a SQL literal here needs the backslashes doubled AGAIN — four in
the INSERT statement — or the column ends up holding `\s`, the runner emits `\s`,
and Spark parses it to a literal `s`. Every email and phone rule then silently
matches the wrong thing.

`verify_seed.sql`, emitted alongside, checks the round-trip by comparing
length(rule_expr) against the fixture. That is the cheapest unambiguous test that
the escaping survived, and it is why this script emits it.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import pandas as pd

FIX = pathlib.Path(__file__).parent.parent / "fixtures" / "out"
OUT = pathlib.Path(__file__).parent / "out"

TABLES = ["config.rule_registry", "config.playbook", "config.cde_registry"]

BINDING_FIELDS = [
    ("target_table", "s"), ("target_column", "s"), ("populated_when", "s"),
    ("expected_scope_filter", "s"), ("binding_status", "s"),
    ("discovered_by", "s"), ("confidence", "n"),
]


def sql_lit(v) -> str:
    """A Spark SQL literal. Backslashes are doubled — see the module header."""
    if v is None or (isinstance(v, float) and pd.isna(v)) or v is pd.NaT:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, pd.Timestamp):
        return f"TIMESTAMP '{v.strftime('%Y-%m-%d %H:%M:%S')}'"
    s = str(v).replace("\\", "\\\\").replace("'", "\\'")
    return f"'{s}'"


def binding_lit(b, rewrite) -> str:
    fields = []
    for name, kind in BINDING_FIELDS:
        v = b.get(name)
        if name == "target_table" and v is not None:
            v = rewrite.get(v, v)
        fields.append(f"'{name}', {sql_lit(v)}")
    return "named_struct(" + ", ".join(fields) + ")"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", default="sdpt_data_trnf")
    ap.add_argument("--schema", default="udp_brnz")
    ap.add_argument("--prefix", default="dq_")
    ap.add_argument("--src-prefix", default="dq_mock_")
    a = ap.parse_args()

    q = f"{a.catalog}.{a.schema}."
    rewrite = {
        "prod.customer.ctct_c": f"{q}{a.src_prefix}ctct_c",
        "prod.customer.subs_c": f"{q}{a.src_prefix}subs_c",
    }

    OUT.mkdir(exist_ok=True)
    parts = [
        "-- =====================================================================",
        "-- seed.sql — GENERATED by sql/seed.py. Do not edit; re-generate.",
        f"-- target: {a.catalog}.{a.schema}, prefix {a.prefix}",
        "--",
        "-- 51 config rows from fixtures/out/. Nothing in results.* is seeded —",
        "-- check_run is what the check runner is meant to produce, and seeding it",
        "-- would defeat the point of running the rules for real.",
        "--",
        "-- target_table rewritten:",
    ]
    for k, v in rewrite.items():
        parts.append(f"--   {k}  ->  {v}")
    parts += [
        "--",
        "-- Re-runnable ONLY after deleting the rows: rule_registry and cde_registry",
        "-- are delta.appendOnly, so a second run APPENDS duplicate versions rather",
        "-- than failing. It will not error — it will quietly double your registry.",
        "-- =====================================================================",
        "",
    ]

    counts, expr_lens = {}, []
    for t in TABLES:
        df = pd.read_parquet(FIX / f"{t}.parquet")
        tgt = f"{q}{a.prefix}{t.replace('.', '_')}"
        counts[tgt] = len(df)

        if "target_table" in df.columns:
            df = df.copy()
            df["target_table"] = df["target_table"].map(lambda x: rewrite.get(x, x))

        parts.append(f"\n-- ---------- {tgt}  ({len(df)} rows) ----------")
        parts.append(f"INSERT INTO {tgt}\n  ({', '.join(df.columns)})\nVALUES")

        rows = []
        for _, r in df.iterrows():
            vals = []
            for c in df.columns:
                v = r[c]
                if c == "bindings":
                    vals.append("array(" + ", ".join(binding_lit(b, rewrite) for b in v) + ")")
                else:
                    vals.append(sql_lit(v))
            rows.append("  (" + ", ".join(vals) + ")")
        parts.append(",\n".join(rows) + ";")

        if "rule_expr" in df.columns:
            expr_lens = [(r.rule_id, int(r.rule_version), len(r.rule_expr))
                         for _, r in df.iterrows()]

    (OUT / "seed.sql").write_text("\n".join(parts) + "\n")

    # ---- the round-trip check -------------------------------------------------
    reg = f"{q}{a.prefix}config_rule_registry"
    v = [
        "-- =====================================================================",
        "-- verify_seed.sql — GENERATED by sql/seed.py.",
        "--",
        "-- Row counts, and the one check that matters: rule_expr length.",
        "-- A short rule_expr means backslashes collapsed on the way in, and every",
        "-- regex rule will then match the wrong thing while looking perfectly fine.",
        "-- =====================================================================",
        "",
        "-- 1. Row counts. Expected: 35, 6, 10.",
    ]
    for tgt, n in counts.items():
        v.append(f"SELECT '{tgt}' AS t, count(*) AS actual, {n} AS expected FROM {tgt};")
    v += [
        "",
        "-- 2. rule_expr round-trip. EXPECTED: zero rows.",
        "--    Any row here is an escaping failure — do not proceed to the check runner.",
        f"WITH expected(rule_id, rule_version, len) AS (VALUES",
    ]
    v.append(",\n".join(f"  ('{rid}', {ver}, {ln})" for rid, ver, ln in expr_lens) + "\n)")
    v += [
        "SELECT e.rule_id, e.rule_version, e.len AS expected_len,",
        "       length(r.rule_expr) AS actual_len",
        f"FROM   expected e",
        f"JOIN   {reg} r ON r.rule_id = e.rule_id AND r.rule_version = e.rule_version",
        "WHERE  length(r.rule_expr) <> e.len;",
        "",
        "-- 3. Eyeball one. EXPECTED: the regex shows DOUBLE backslashes, e.g. [^@\\\\s.]",
        f"SELECT rule_expr FROM {reg} WHERE rule_id = 'CTCT_EML_FMT';",
        "",
        "-- 4. Every rule now points at a table that exists. EXPECTED: zero rows.",
        f"SELECT DISTINCT target_table FROM {reg}",
        "WHERE  target_table LIKE 'prod.%';",
    ]
    (OUT / "verify_seed.sql").write_text("\n".join(v) + "\n")

    print("wrote sql/out/seed.sql")
    for tgt, n in counts.items():
        print(f"    {n:3} rows -> {tgt}")
    print("\nwrote sql/out/verify_seed.sql — run it after seeding, before the check runner")
    print(f"\nsource tables rewritten to:")
    for k, val in rewrite.items():
        print(f"    {k}  ->  {val}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
